DutchTreat/DutchTreat/ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace DutchTreat.ViewModels
{
    public class ContactViewModel
    {
        [Required]
        [MinLength(5)]
        public string Name { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Subject { get; set; }

        [Required]
        [MaxLength(250, ErrorMessage ="Too many characters")]
        public string Message { get; set; }
    }
}

DutchTreat/DutchTreat/Controllers/AppController.cs
using DutchTreat.data;
using DutchTreat.Services;
using DutchTreat.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DutchTreat.Controllers
{
    public class AppController:Controller
    {
        private readonly IMailService _mailService;
        private readonly IDutchRepository _repository;

        public AppController(IMailService mailService, IDutchRepository repository)
        {
            _mailService = mailService;
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("contact")]
        public IActionResult Contact()
        {
            ViewBag.Title = "Contact us";

            return View();
        }

        [HttpPost("contact")]  //the form has a method post
        public IActionResult Contact(ContactViewModel model)
        {
            if(ModelState.IsValid)
            {
                _mailService.SendMessage("sean", model.Subject, $"From: {model.Name} - {model.Email}, Message: {model.Message}");
                ViewBag.UserMessage = "Mail Sent";
                ModelState.Clear();
            }
            else
            {

            }

            return View();
        }

        public IActionResult AboutUs()
        {
            return View();
        }

        public IActionResult Shop()
        {
            var results = _repository.GetAllProducts();

            return View(results);
        }
    }
}

DutchTreat/DutchTreat/Controllers/OrdersController.cs
using DutchTreat.data;
using DutchTreat.data.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DutchTreat.Controllers
{
    [Route("api/[Controller]")]
    public class OrdersController:Controller
    {
        private readonly IDutchRepository _repository;

        public OrdersController(IDutchRepository repository)
        {
            _repository = repository;
        }

        [HttpGet]
        public IActionResult Get()
        {
            try
            {
                return Ok(_repository.GetAllOrders());
            }
            catch (Exception ex)
            {
                return BadRequest("Failed to get products");
            }
        }

        [HttpGet("{id:int}")]
        public IActionResult Get(int id)
        {
            try
            {
                var order = _repository.GetOrderById(id);
                if (order != null)
                    return Ok(order);
                else
                    return NotFound();

            }
            catch (Exception ex)
            {
                return BadRequest("Failed to get products");
            }
        }

        [HttpPost]
        public IActionResult Post([FromBody]Order Model)  //frombody gets data
        {
            try
            {
                _repository.AddEntity(Model);
               // _repository.SaveChanges(); //change to save all

                if (_repository.SaveChanges())
                {
                    return Created($"/api/orders/{Model.Id}", Model);  //use created on a post
                }
               
            }
            catch (Exception ex)
            {
                return BadRequest("Failed to save");
            }
            return BadRequest("Failed to save");
        }
    }
}

DutchTreat/DutchTreat/Controllers/ProductsController.cs
using DutchTreat.data;
using DutchTreat.data.Entities;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DutchTreat.Controllers
{
    [Route("api/[Controller]")]
    public class ProductsController:Controller
    {
        private readonly IDutchRepository _repository;

        public ProductsController(IDutchRepository repository)
        {
            _repository = repository;
        }

        [HttpGet]
        public IActionResult Get()
        {
            try
            {
              return Ok(_repository.GetAllProducts());
            }
            catch(Exception ex)
            {
                return BadRequest("Failed to get products");
            }
            
        }
    }
}

DutchTreat/DutchTreat/Views/App/About.cshtml
<h2>About us</h2>
<p>More to follow</p>

DutchTreat/DutchTreat/Views/App/Contact.cshtml
@model ContactViewModel
@{
    ViewBag.Title = "Contact Us";
}
@section scripts {
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

<div class="col-md-6 col-md-offset-3">
    <div class="well">
        <form method="post">
            <div asp-validation-summary="ModelOnly"></div>
            <!--asp-for you select this it puts the focus on the textbox-->
            <div class="form-group">
                <label asp-for="Name">Your Name:</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email">Email:</label>
                <input type="email" asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Subject">Subject:</label>
                <input type="text" asp-for="Subject" class="form-control" />
                <span asp-validation-for="Subject" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Message">Message:</label>
                <textarea rows="4" asp-for="Message" class="form-control"></textarea>
                <span asp-validation-for="Message" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-lg"><i class="fa fa-envelope"></i> Send Message</button>
                <div class="text-success">@ViewBag.UserMessage</div>
            </div>
        </form>
    </div>
</div>

DutchTreat/DutchTreat/Views/App/Shop.cshtml
@model IEnumerable<Product>
<h1>Shop</h1>
<p>Count: @Model.Count()</p>

@foreach (var p in Model)
{
    <div class="col-md-3">
        <div class="well well-sm">
            <img src="~/img/@(p.ArtId).jpg" class="img-responsive" alt="@p.Title" />
            <h3>@p.Category - @p.Size</h3>
            <ul class="product-props">
                <li>Price: @p.Price</li>
                <li>Artist: @p.Artist</li>
                <li>Title: @p.Title</li>
                <li>Description: @p.ArtDescription</li>
            </ul>
            <button id="buyButton">Buy</button>
        </div>
    </div>
}

DutchTreat/DutchTreat/Views/App/index.cshtml
@{ 
    ViewBag.Title = "Home Page";
}
<div class="row">
    <div class="col-md-6">
        <div class="product-info">
            <img src="~/img/VanGogh.jpg" />
            <h3>Mug</h3>
            <ul class="product-props">
                <li>Price: €9.99 </li>
                <li>Artist: Van Gogh </li>
                <li>Title:</li>
                <li>Description: Self-portrait</li>
            </ul>
            <button id="buyButton" class="btn btn-success">Buy</button>
        </div>
        <div id="theForm">
            <form>
                <label>Your Name:</label>
                <br />
                <input />
                <br />
                <label>Email:</label>
                <br />
                <input type="email" />
                <br />
                <label>Subject:</label>
                <br />
                <input type="text" />
                <br />
                <label>Subject:</label>
                <br />
                <textarea rows="4"></textarea>
                <br />
                <input type="submit" value="Send Message" />
            </form>
        </div>

        <div>
            <div id="loginToggle">Login</div>
            <form class="popup-form">
                <div>
                    <label>Username</label>
                    <input />
                </div>
                <div>
                    <label>Password</label>
                    <input />
                </div>
                <div>
                    <input type="checkbox" />
                    <label>Remember Me?</label>
                </div>
                <div>
                    <input type="submit" value="login" />
                </div>
            </form>
        </div>
    </div>
</div>

DutchTreat/DutchTreat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Dutch Treat: @ViewBag.Title</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse">
        <header class="container">
            <div class="navbar-header">
                <div class="navbar-brand"><i class="fa fa-paint-brush"></i> Dutch Treat</div>
                <button class="navbar-toggle" data-toggle="collapse" data-target="#menu">&#9776;</button>
            </div>
            <div id="menu" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="App" asp-action="Index">Home</a></li>
                    <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
                    <li><a asp-controller="App" asp-action="About">About</a></li>
                </ul>
            </div>
        </header>
    </div>

    <section class="container">
        <h2 class="text-center">@ViewBag.Title</h2>
        @RenderBody()
    </section>

    <footer class="container">
        <div class="text-center">Copyright 2017 Dutch Treat LLC</div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/index.js"></script>
    @RenderSection("scripts", false)
</body>
</html>